### ISSUE TITLE
translate produces pom.xml with maven-4.1.0.xsd

### ISSUE THREAD

**Issue by lefou** [takari/polyglot-maven#102]
The new XML schema version 4.1.0, which essentially introduces attributes for various elements, is not compatible to various IDEs.

IMHO, the `pom.xml` should stay as compatible as possible and avoid to be incompatible with current Maven tools like Eclipse or IntellJ Idea. **Thus, we should stay with XSD version 4.0.0!** The translation to `pom.xml`  files is typically used in polyglot projects as a compatiblity bridge. Requiring support for the bleading edge `pom.xml` format isn't helpful.

Background: We migrated a large multi-project to polyglot-scala. To use IDEs we translate our `pom.scala` files to `pom.xml`. Unfortunately, newer versions of the translate-plugin (> 0.1.15) produce XML with attributes, which do not work with IDEs.

**Comment by lefou** [comment]
I suggest to revert 1a787054cddbbdde1ae1fa3a998876be2d190351 which was introduced via PR #92 .

**Comment by sveryovka** [comment]
I think that in fact I it is not really related to PR #92. Schema v 4.1 for polyglot-xml was introduced before that.
This issue is caused by behavior of canParse method in 
polyglot-xml/src/main/java/org/sonatype/maven/polyglot/xml/XMLMapping.java changed after that PR. 

Looks like it either has to be reverted to original version with org.sonatype.maven.polyglot.xml.xpp3.MavenXpp3Reader or add special clause to return "false" in case if file extension is "xml" but file does not exists.

I will see if I can look at this deeper next week or in a weeks.

**Comment by lefou** [comment]
I can't judge if a revert is more suitable than a change, as I don't know the motivation behind the change to `XMLMapping.java`. But I would strongly advice to not generate different target files only by the fact that a file (`pom.xml`) exists or not. It would also break our/my workflow, as we typically regenerate all `pom.xml` files, no matter whether they are missing or just outdated.

**Comment by sveryovka** [comment]
Revert is not suitable. I want to understand what finding you had to understand all of the aspects of the issue. Can you please explain findings you had which led you to to suggesting it?

**Comment by lefou** [comment]
You are right, reverting PR #92 does not fix the issue. I must have mixed up various versions in local repository while testing it. In short, I searched a bit in history, reverted the PR and for some reasons the generated poms in my project looked good (for a while). But obviously it must have been some other change. So, please ignore my suggestion as a solution.

The main issue remains, though. We should not generate `pom.xml`'s with attributes for dependency details.

**Comment by lefou** [comment]
You are right, reverting PR #92 does not fix the issue. I must have mixed up various versions in local repository while testing it. In short, I searched a bit in history, reverted the PR and for some reasons the generated poms in my project looked good (for a while). But obviously it must have been some other change. So, please ignore my suggestion as a solution.

The main issue remains, though. We should not generate `pom.xml`'s with attributes for dependency details.

**Comment by ppiastucki** [comment]
Is not it enough to simply switch from PolyglotMavenXpp3Writer to org.apache.maven.model.io.xpp3.MavenXpp3Writer? 
It looks like Maven model 4.1.0 is going nowhere (https://issues.apache.org/jira/browse/MNG-6082) so the XML output currently produced by polyglot-xml is pretty useless.

**Comment by lefou** [comment]
Closing, as this is no longer an issue with version 0.2.0.
