### ISSUE TITLE
Accessing build environment from groovy

### ISSUE THREAD

**Issue by szantopeter** [takari/polyglot-maven#106]
Is it possible to access build environment and properties from a groovy build script? Scala seems to have access to an ec variable like this

```
tasks = Seq(Task("someTaskId", "verify") { ec =>
  println(s"I'm Scala running during the verify phase. The ec passed in allows me to access the project, e.g. the baseDir: ${ec.basedir}")
})
```

but I couldn't figure out how to do the same in groovy (and there was no example for that either)

**Comment by szantopeter** [comment]
@jvanzyl any idea?

**Comment by szantopeter** [comment]
I created a pull request to address this https://github.com/takari/polyglot-maven/pull/116

**Comment by mosabua** [comment]
Already released
