### ISSUE TITLE
Interoperability story

### ISSUE THREAD

**Issue by lefou** [takari/polyglot-maven#112]
Is the section "Note of caution" from the `README.md` still valid?

I work regularly with the Scala DSL, and there are no issues at all. The use of `pom.scala` is completely transparent. Maven installs proper `pom.xml` files into the local repository.

**Comment by mosabua** [comment]
We might want to weaken the note a bit.

**Comment by lefou** [comment]
Any comments for other DSLs? Is the `pom.xml`installation thing working for other DSLs, too? 

If so, I would change the README text. IMHO, the left interoperability issues are IDE/editor integration of pom files when using non-XML DSLs.

**Comment by lefou** [comment]
I'm closing this, as it works for me. It would be great though, if other could check their preferred polyglot dialect and update the `README.md`.
