### ISSUE TITLE
[Request] Add Urbanise.com in "Polyglot Maven in Real Life" section

### ISSUE THREAD

**Issue by petromir** [takari/polyglot-maven#134]
Hi,

I'm one of the back-end developers in [https://urbanise.com/](https://urbanise.com/) and we use `polyglot-maven` with YAML for our enterprise software.

Could you please add us in "Polyglot Maven in Real Life" section

Thanks!

**Comment by mosabua** [comment]
Sure... send a PR with some details and I will merge.

**Comment by petromir** [comment]
Done - https://github.com/takari/polyglot-maven/pull/136
