### ISSUE TITLE
Add gitter chat room as an easy way to ask and get into contact 

### ISSUE THREAD

**Issue by lefou** [takari/polyglot-maven#138]

**Comment by mosabua** [comment]
To be honest I would rather not have yet another chat to hang out in.

**Comment by lefou** [comment]
So, where is the preferred chat for polyglot users?

**Comment by mosabua** [comment]
I would think its the normal Maven users and dev lists at this stage.

**Comment by jvanzyl** [comment]
We can use freenode #polyglot-maven

**Comment by lefou** [comment]
My personal issue with freenode or IRC in general is, that you can not have async conversations and notifications without staying permanently online.
Whereas Gitter is well integrated with Github and has proper history search and notifications. This is IMHO just easier for an random user or dev with a question. I found myself more than once in such a situation and in the end dropped the urge to ask/contribute at all because a new ticket or a email where not the right thing or simply not easy enough.

**Comment by h2000** [comment]
+1

**Comment by lefou** [comment]
What ever place will/should be the right one for discussions, there should be some link to it in the README. Even now, that I know I could use IRC #maven, I still don't know how to ping a specific developer on #maven (@huntc who I think contributed most of the scala dialect). And #polyglot-maven is currently empty. Dropping a note there would of course almost never be seen by anyone.

I'm not that convinced, that we _should not_ add a Gitter room. But of course, I can't add it, I'm just an contributor. So I have to convince you, the devs in charge.

**Comment by mkristian** [comment]
my 2 cents: I have to admit I am not on IRC anymore for some time now. prefer the async nature of gitter.

**Comment by mosabua** [comment]
https://gitter.im/takari

**Comment by mosabua** [comment]
Added badge to readme as well and will add to other repos.

**Comment by lefou** [comment]
@mosabua Great, thanks! But currently, I can't see any room. As far as I know, the organization-level rooms are only visible for organization members, which I'm not. I was expecting a project-specific room under  https://gitter.im/takari/polyglot-maven, which would then be open for all users.

**Comment by mosabua** [comment]
Dang ...I would rather not have a repo specific one.. let me check

**Comment by mosabua** [comment]
https://gitter.im/takari/AllThingsTakari
