### ISSUE TITLE
Cut 0.3.0  release

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#139]
I am planning to cut another release asap but I kind of think should move on from 0.x to 1.0+ ..

There are a number of projects that have been using polyglot in "production" for quite a while now and I think that warrants using 1.0+ 

wdyt @takari/polyglot ..

**Comment by lefou** [comment]
IMHO, for 1.0.0, we should at least clarify, if the warnings (section "Note of Caution") on the README.md still hold.

**Comment by mosabua** [comment]
Afaik the note of caution still stands .. but that does not necessarily mean it cant be 1.0.0 imho anyway

**Comment by mosabua** [comment]
0.3.0 it will be shortly..

**Comment by mosabua** [comment]
https://github.com/takari/polyglot-maven/tree/polyglot-0.3.0

and in central as well
