### ISSUE TITLE
Would it be possible to split pom.xxx descriptor?

### ISSUE THREAD

**Issue by aruizca** [takari/polyglot-maven#176]
Hi Jason,

first all thanks for your work. Big fan of yours :-)

I am interesting in using either Groovy or Kotlin for the pom descriptor and I was wondering if there is any way to extract parts of the descriptor (eg: dependencies) to a separate file.

I know there is Maven tiles but it seems there are problems when using it along with this.

Cheers,

**Comment by lefou** [comment]
I know for sure in the Scala dialect, you can include other Scala files. E.g. you could define your dependencies in the included file and reference them in the POM construction. 
I was told, that with the Groovy dialect, includes are also possible, but can't tell you how to do it exactly.

**Comment by aruizca** [comment]
Thanks for your help guys! We'll give it a go.
