### ISSUE TITLE
Need release to help stabilize properties from JDK 8 to JDK 11

### ISSUE THREAD

**Issue by headius** [takari/polyglot-maven#177]
JDK 9+ appear to order properties differently in Properties objects, resulting in polyglot-generated XML files flopping back and forth between the two orders.

In  60290957cfc693fa8ad44711702b91c95f60f692, @mkristian updated the logic to always emit the properties in sorted order, so they are stable in the resulting XML.

We request a release, since JRuby is attempting to better support Java 9+ (specifically Java 11) and we version our generated pom.xml files.

**Comment by mosabua** [comment]
http://repo.maven.apache.org/maven2/io/takari/polyglot/polyglot-ruby/0.3.2/ and others are all there now

**Comment by mosabua** [comment]
Updated examples to release and created tag. Updated again to new dev version and pushed to master. 

Also filed https://github.com/takari/polyglot-maven/issues/178 as a result

**Comment by mosabua** [comment]
All done now. Enjoy @headius @mkristian @takari/polyglot and others.

**Comment by mkristian** [comment]
@mosabua thank you for the release.
