### ISSUE TITLE
Kotlin example untied

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#178]
The kotlin examples uses a parent and dependencies from the polyglot-kotlin implementation. This should all be removed so that the project is a true stand-alone project and just uses the kotlin extension.

**Comment by mosabua** [comment]
Can you please have look @Tradunsky

**Comment by Tradunsky** [comment]
@mosabua Sure.

**Comment by Tradunsky** [comment]
https://github.com/takari/polyglot-maven-examples/pull/10
