### ISSUE TITLE
Incompatibility with maven-release

### ISSUE THREAD

**Issue by kutschkem** [takari/polyglot-maven#188]
Maven release spawns a child maven process for the preparationGoals / completionGoals. This interferes with the temporary pom files, because they get deleted early by the child process. If subsequent goals try to do something with the pom files (as does the maven release plugin), then that fails because the files are missing.

See this StackOverflow answer: https://stackoverflow.com/a/56661135/1319284

**Comment by mosabua** [comment]
This is known issue. Just dont use the release plugin.
