### ISSUE TITLE
Release 0.4.2 / 0.4.3

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#189]
to get https://github.com/takari/polyglot-maven/pull/187 out

**Comment by mosabua** [comment]
Merge done, release build to oss.sonatype.org done, sync to central started, should be there soon

still have to fix changelog, examples and announce .. but this should enable the blog post from @lion7

**Comment by lion7** [comment]
Woohoo, thanks a lot @mosabua :smile:

**Comment by mosabua** [comment]
I will do rest in the evening or over weekend or so...

**Comment by mosabua** [comment]
Let me know about the post when its up! ,, we should add to the readme..

**Comment by lion7** [comment]
Will do! I expect it to be published early next week.

**Comment by mosabua** [comment]
I will release 0.4.3 with the recent PR fix

**Comment by lion7** [comment]
My blog is published: https://craftsmen.nl/polyglot-maven-kotlin-instead-of-xml/

Feel free to link to it from the readme or anywhere else

**Comment by mosabua** [comment]
So .. tried to cut the release 0.4.3 .. but I am getting these sort of errors in the build. Any idea why that might be the case @thorntonrp @lion7 

```
[ERROR]   KotlinModelReaderTests.test#example:10->doTest:22->AbstractModelTestCase.assertEquals:57 expected:<...       <version>0.4.[2-SNAPSHOT</version>
        <executions>
          <execution>
            <id>hello</id>
            <phase>initialize</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <taskId>hello</taskId>
              <nativePom>pom.kts</nativePom>
            </configuration>
          </execution>
          <execution>
            <id>hello-script</id>
            <phase>process-resources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <taskId>hello-script</taskId>
              <nativePom>pom.kts</nativePom>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>io.takari.polyglot</groupId>
            <artifactId>polyglot-kotlin</artifactId>
            <version>0.4.2]-SNAPSHOT</version>
...> but was:<...       <version>0.4.[3-SNAPSHOT</version>
        <executions>
          <execution>
            <id>hello</id>
            <phase>initialize</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <taskId>hello</taskId>
              <nativePom>pom.kts</nativePom>
            </configuration>
          </execution>
          <execution>
            <id>hello-script</id>
            <phase>process-resources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <taskId>hello-script</taskId>
              <nativePom>pom.kts</nativePom>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>io.takari.polyglot</groupId>
            <artifactId>polyglot-kotlin</artifactId>
            <version>0.4.3]-SNAPSHOT</version>
...>
```

**Comment by mosabua** [comment]
Found that the project version is hardcoded in some of the test resources.... we should fix this. For now I will try to update and cut a release without fixing just to get it shipped

**Comment by mosabua** [comment]
release build now running.

**Comment by mosabua** [comment]
Release built and published to ossrh and started sync to central. Pushed tag.

**Comment by mosabua** [comment]
Updated hardcoded version in kotlin tests and filed https://github.com/takari/polyglot-maven/issues/190

**Comment by mosabua** [comment]
Updated examples project

**Comment by mosabua** [comment]
All done .. ready for next one ;-)

**Comment by lion7** [comment]
I'll create a new PR where the version is no longer hardcoded. I introduced this in my last PR where I refactored the tests so they work with Plexus.
Hopefully this will be somewhere next week

**Comment by mosabua** [comment]
No rush ... and sounds great!

**Comment by lion7** [comment]
Related issue is https://github.com/takari/polyglot-maven/issues/191
