### ISSUE TITLE
Avoid hardcoded version in kotlin tests

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#191]
We need to get rid of this stuff. Its a maintenance headache.

https://github.com/takari/polyglot-maven/commit/c0ffcf4e7f748d7cba4d761b0133761b8d2c6c57

Maybe do some filtering of the test resources before the test run .. or otherwise remove it somehow? Why are these needed anyway?

Any idea @lion7 or @thorntonrp ?

**Comment by mosabua** [comment]
@lion7 mentioned he will work on this ..

**Comment by lion7** [comment]
I intended enable filtering on the test resources and use a custom delimiter to prevent accidentally replacing other placeholders in the `pom.xml` and `pom.kts` files. Unfortunately providing a custom delimiter is possible with the default resources plugin ([link](https://maven.apache.org/plugins/maven-resources-plugin/testResources-mojo.html#delimiters)) but that doesn't seem to be supported by the takari lifecycle plugin ([link](https://github.com/takari/takari-lifecycle/blob/master/takari-lifecycle-plugin/src/main/java/io/takari/resources/filtering/FilterResourcesProcessor.java)).

Any thoughts @mosabua ?

**Comment by lion7** [comment]
I figured that the maven-replacer-plugin ([link](https://code.google.com/archive/p/maven-replacer-plugin/)) would also fit the bill.
See https://github.com/lion7/polyglot-maven/tree/issue-191 for my current progress.
The unit tests are okay now but the integration test still fails with some weird `ClassCastException` :cry:

**Comment by lion7** [comment]
@mosabua I opened #199 that addresses this issue (and also a bug fix for another small issue)
