### ISSUE TITLE
org.sonatype.maven.polyglot.PolyglotModelManager.getSortedMappings() sorts in wrong direction

### ISSUE THREAD

**Issue by laeubi** [takari/polyglot-maven#209]
[PolyglotModelManager.getSortedMappings](https://github.com/takari/polyglot-maven/blob/master/polyglot-common/src/main/java/org/sonatype/maven/polyglot/PolyglotModelManager.java#L49) sorts the given mappings, but this is sorted by default with lowest first. So contrary to the API description mappings with a LOWER priority are asked first!

Simple fix would be to use [Collections.reverseOrder](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#reverseOrder(java.util.Comparator))

**Comment by laeubi** [comment]
@mosabua Is this fix included in the 0.4.5 release?

**Comment by mosabua** [comment]
Yes.. https://github.com/takari/polyglot-maven/commits/master
