### ISSUE TITLE
Editor support

### ISSUE THREAD

**Issue by cemo** [takari/polyglot-maven#216]
Hi,  after some time, I wanted to revisit polyglot support of maven. I am using Ruby support which seems so elegant and readable. The command line seems working flawless but editor IntelliJ IDE support is terrible. Is there someone else who is suffering from it as well? Maybe there is some folks from Jetbrains can help us?

**Comment by mosabua** [comment]
Any IDE developers can start supporting the various dialects .. the team running this project does not have the resources or time to work on this.
