### ISSUE TITLE
Maven deploy goal fails with -f because of missing .polyglot.pom.*

### ISSUE THREAD

**Issue by thorntonrp** [takari/polyglot-maven#220]
When running `mvn -f path/to/pom.kts deploy` (or any other polyglot pom), the command fails because the polyglot `pom.kts` is installed to the local repository instead of `pom.xml`. This is due to the temporary file `.polyglot.pom.kts` not being produced by the TeslaModelProcessor because the `-f` argument prevents the `locatePom` method from getting called.

This error can be verified by running `mvn -f path/to/pom.kts install` and seeing that the contents of the pom that gets installed into the local repository is from the polyglot pom instead of the xml pom.

I have a fix that resolves this issue. I will submit it in a PR shortly.

**Comment by mosabua** [comment]
0.4.6 is out
