### ISSUE TITLE
NPE when mvn deploy:deploy-file a pomless JAR

### ISSUE THREAD

**Issue by delanym** [takari/polyglot-maven#226]
Subject says it all. Maven 3.6.3

**Comment by laeubi** [comment]
See eclipse/tycho#97

**Comment by mdaloia** [comment]
@jvanzyl Do you have any roadmap/date in mind to release 0.4.7 so this fix is included?
We hit this same issue through Tycho.
Thanks in advance

**Comment by jvanzyl** [comment]
I added a GHA workflow for CI. So let's try to get a clean build and I can cut a release.
