### ISSUE TITLE
Get GHA working on master

### ISSUE THREAD

**Issue by jvanzyl** [takari/polyglot-maven#233]
I tried this for the first time, and it appears that the scala module is having issues.

@mosabua is the scala module been having issues lately?

My suggestion would be to put each of the modules that are not working on their own branch, and if anyone wants to tackle fixing them up they can.

**Comment by jvanzyl** [comment]
Ok, the GHA CI is working now. Right now it's using Java11 to build, is this an issue for anyone? I'll wait until the morning to cut a release to see if anyone wants me to set this to Java8 for any reason.

@headius is Java11 an issue for JRuby?

**Comment by mosabua** [comment]
I think Java 11 is ok for JRuby .. but not sure if everything will build on the jruby module .. 

Scala has been fine
