### ISSUE TITLE
Generate a standard pom.xml for interop

### ISSUE THREAD

**Issue by jvanzyl** [takari/polyglot-maven#25]
We need a general way to generate and attach a standard pom.xml file as part of a polyglot build.

**Comment by mosabua** [comment]
@jvanzyl that standard xml file should probably be the main pom for install and deploy of the project right? And the polyglot one should be the attached one? Unless we use something like

test-1.2.3.pom
test-1.2.3-javadoc.jar
test-1.2.3.jar
and the polyglot one uses a new standard like

test-1.2.3.pom.rb
test-1.2.3.pom.groovy 

but that might some clients tools in terms of file name parsing or assmbling so maybe safer would be

test-1.2.3.pomrb
test-1.2.3-pomgroovy

**Comment by jvanzyl** [comment]
Yes, I mean that pom.xml would be the one that is expected for deployment and normal consumption.

**Comment by mosabua** [comment]
But you would still attach the polyglot one somehow right? Or not? I think it might be useful to have it in the repo by default and have some sort of standard naming convention.

**Comment by jvanzyl** [comment]
Sure, there is no harm in having it there but currently it would end up as a classified artifact. Which is fine.

**Comment by mosabua** [comment]
Just to be clear it would be something like

test-1.2.3-groovy.pom
test-1.2.3-rb.pom

right?

**Comment by jvanzyl** [comment]
Yup

**Comment by mosabua** [comment]
Sounds good thx. That will probably work easily with other tools. Its just another classified artifact.

**Comment by michaelwiles** [comment]
This would be so cool...

I assume it would be possible to write the generated maven model back to xml format? Is tooling already available to do that?

**Comment by mosabua** [comment]
The standard pom can already be created by the ruby dialect. I think the groovy dialect can do that already as well but I am not 100% sure.

**Comment by lefou** [comment]
@michaelwiles Have a look at the README of this project. There you find some info how to use the polyglot-translate-plugin to convert between various dialects including `xml`. If you use groovy or scala dialect, polyglot-maven automatically installs and deploys a `pom.xml` in the repository.
