### ISSUE TITLE
How to can I start with it?

### ISSUE THREAD

**Issue by nvoynov** [takari/polyglot-maven#29]
Hello, developers!

This projects is 'breath of fresh air for me' because I worked with Ruby some time and I like it very much. You need small adopt time and Ruby is like an good habit.

I have installed Ruby (for windows with devkit), JDK and Maven, I have done some small self-education projects in maven way. Currently I want to start with Maven RubyDSL configuration of pom.xml. How to can I do it? Standard Ruby distrubutive is enough or I need JRuby?

Can I translate current pom.xml files to .rb? I read the article http://takari.io/2015/01/28/ruby-dsl.html. It's excellent but how to start?

**Comment by mkristian** [comment]
first you needs mvn 3.3.1+

second you need a .mvn/extensions.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
  <extension>
    <groupId>io.takari.polyglot</groupId>
    <artifactId>polyglot-ruby</artifactId>
    <version>0.1.7</version>
  </extension>
</extensions>
```

no need to install ruby or jruby - maven will take care of this.

translate a pom.xml to pom.rb see 
http://takari.io/2015/03/21/polyglot-maven.html

for an quick overview of the ruby dsl have a look at (all three pom.rb files are equivalent):
https://github.com/torquebox/maven-tools/tree/master/spec/pom_maven_style
https://github.com/torquebox/maven-tools/tree/master/spec/pom_maven_hash_style
https://github.com/torquebox/maven-tools/tree/master/spec/pom_maven_alternative_style

**Comment by nvoynov** [comment]
Thank you very much!

**Comment by paulvi** [comment]
Please copy "How to start" into README

**Comment by lefou** [comment]
I would say, all relevant information is now in the README, and this issue can be closed. /cc @jvanzyl
