### ISSUE TITLE
XML use attribute replace sub element

### ISSUE THREAD

**Issue by beihaifeiwu** [takari/polyglot-maven#30]
Do you have any plan to improve the xml schema and use attribute to replace sub element ？ in this way many config can be write in one line just like spring did。

        <dependency>
            <groupId>aopalliance</groupId>
            <artifactId>aopalliance</artifactId>
            <version>1.0</version>
        </dependency>

can be wirten in:

        <dependency  groupId="aopalliance" artifactId="aopalliance" version="1.0" />

attribute name can be make shoter

**Comment by jvanzyl** [comment]
The official XML formats are more the domain of the Apache Maven Project. We've talked about changing the format but this requires what we call the consumer POM. Regardless of the format the build POM is in we need emit a model version 4.0.0 consumer pom.xml as part of the build. Until this work is done it's not easy to think about this as it's required for interop across versions of Maven. This work needs to be done to make Polyglot fully functional as well. So the technical unpinning to do this will be present shortly.

**Comment by beihaifeiwu** [comment]
Thanks for your explain ! but I wonder if it can be pretend to change the format, just add another middle layer to translate the attribute to the sub element。No need to translate all element just the dependency is also a good one, what do you think?
