### ISSUE TITLE
Translate to pom.xml mishandled XML entity

### ISSUE THREAD

**Issue by binkley** [takari/polyglot-maven#35]
Neat - I can run the translator in reverse to generate pom.xml from pom.yml.

However roundtrip failed for an XML entity, in this creating extra entries for `MANIFEST.MF`:

Source `pom.xml` contains

``` XML
<Built-By>B. K. Oxley (binkley) &lt;binkley@alumni.rice.edu&gt;</Built-By>
```

Generated `pom.yml` contains:

``` YAML
Built-By: B. K. Oxley (binkley) binkley@alumni.rice.edu>
```

Roundtrip translate back to XML contains (note the `>` near the end of the line):

``` XML
<Built-By>B. K. Oxley (binkley) &lt;binkley@alumni.rice.edu></Built-By>
```

So interestingly the LT entity was translated back, but the GT entity was not, producing invalid XML.

**Comment by mosabua** [comment]
This is such an edge case. You can work around it simply by using other brackets around your email or just no brackets. I am closing the ticket.
