### ISSUE TITLE
[polyglot-groovy] conversion to pom.groovy should generate dependencies w/ short syntax

### ISSUE THREAD

**Issue by fbricon** [takari/polyglot-maven#49]
Converting this pom.xml

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>foo.bar</groupId>
    <artifactId>example</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

to groovy yields this:

```
project {
  modelVersion '4.0.0'
  groupId 'foo.bar'
  artifactId 'example'
  version '0.0.1-SNAPSHOT'
  dependencies {
    dependency {
      groupId 'junit'
      artifactId 'junit'
      version '4.12'
      scope 'test'
    }
  }
}
```

It'd be great to get an even less verbose output, like:

```
project {
  modelVersion '4.0.0'
  groupId 'foo.bar'
  artifactId 'example'
  version '0.0.1-SNAPSHOT'
  dependencies {
    dependency 'junit:junit:4.12:test'
  }
}
```

as this syntax is already supported

**Comment by Randgalt** [comment]
I agree. One thing Gradle does well is have a very concise GAV representation.

**Comment by jdillon** [comment]
IIRC there is support for dependency(‘junit:junit:4.12:test’) syntax already, just the xml -> groovy pom converter doesn’t use that form.

—jason




On September 14, 2015 at 11:38:41 AM, Fred Bricon (notifications@github.com) wrote:

Converting this pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>foo.bar</groupId>
    <artifactId>example</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>

to groovy yields this:

project {
  modelVersion '4.0.0'
  groupId 'foo.bar'
  artifactId 'example'
  version '0.0.1-SNAPSHOT'
  dependencies {
    dependency {
      groupId 'junit'
      artifactId 'junit'
      version '4.12'
      scope 'test'
    }
  }
}

It'd be great to get an even less verbose output, like:
project {
modelVersion '4.0.0'
groupId 'foo.bar'
artifactId 'example'
version '0.0.1-SNAPSHOT'
dependencies {
dependency 'junit:junit:4.12:test'
}
}

as this syntax is already supported

**Comment by fbricon** [comment]
@jdillon one naive way to implement it, could be to change [Dom2Groovy#print](https://github.com/takari/polyglot-maven/blob/2ef761b7a83b12e3201848566333e734c9dc2497/polyglot-groovy/src/main/java/org/sonatype/maven/polyglot/groovy/Dom2Groovy.java#L82) to something like 
```
  protected void print(final Node node, final Map namespaces, final boolean endWithComma) {
    switch (node.getNodeType()) {
    case Node.ELEMENT_NODE:
      Element elmt = (Element) node;
      if ("dependency".equals(elmt.getNodeName())) {
    	  printDependency(elmt, namespaces, endWithComma));
      } else {
    	  printElement(elmt, namespaces, endWithComma);
      }
      break;
    case Node.PROCESSING_INSTRUCTION_NODE:
      printPI((ProcessingInstruction) node, endWithComma);
      break;
    case Node.TEXT_NODE:
      printText((Text) node, endWithComma);
      break;
    case Node.COMMENT_NODE:
      printComment((Comment) node, endWithComma);
      break;
    }
  }
```
Any advice @jdillon?

**Comment by fbricon** [comment]
Another alternative would be to generate a different xml in [GroovyModelWriter#write](https://github.com/takari/polyglot-maven/blob/2ef761b7a83b12e3201848566333e734c9dc2497/polyglot-groovy/src/main/java/org/sonatype/maven/polyglot/groovy/GroovyModelWriter.java#L54), so <dependency>g:a:v:s<dependency> would be generated instead. That way, no need to change Dom2Groovy

**Comment by jdillon** [comment]
I barely remember how that part of the codebase works.

I do recall when I did this originally I left the output as close to the xml format so that folks would easily understand it, w/o assuming what flavor of config folks prefer.

—jason




On September 14, 2015 at 12:33:40 PM, Fred Bricon (notifications@github.com) wrote:

Another alternative would be to generate a different xml in GroovyModelWriter#write, so gv:s would be generated instead. That way, no need to change Dom2Groovy

**Comment by jdillon** [comment]
Looking at a few other bits reminded me more how this works, and the conversion to groovy is done based on the default model format rendered to xml, then basic translation to groovy based on the parse DOM, so its not really easy w/o adding a lot of complexity to translate groovy to specialized syntax at present.

IMO translation is useful as a starting-point and likely needs a human to make some decisions post-translation to optimize to their desired configuration.

**Comment by mosabua** [comment]
Given 

- age of the issue 
- limited scope of just the generation of pom.groovy from xml
- complexity to implement
- easy workaround by just manually updating a few snippets after conversion manually

I am closing this issue. If anybody feels really strongly about it .. send a PR please.
