### ISSUE TITLE
Translate plugin fails when current path contains spaces

### ISSUE THREAD

**Issue by hban** [takari/polyglot-maven#56]
On Windows, translate plugin fails if the full path to the working directory contains spaces.

Example path: `D:\Documents\x y\test`

    Failed to execute goal io.takari.polyglot:polyglot-translate-plugin:0.1.12:translate (default-cli) on project test: Error translating pom.xml -> pom.yaml: D:\Documents\x%20y\test\pom.yaml (The system cannot find the path specified) -> [Help 1]

**Comment by jdillon** [comment]
This should help: https://github.com/takari/polyglot-maven/pull/59
