### ISSUE TITLE
polyglot-maven don't include the license file

### ISSUE THREAD

**Issue by puntogil** [takari/polyglot-maven#63]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by jvanzyl** [comment]
Feel free to make a pull request.

**Comment by mosabua** [comment]
Been fixed a while ago.
