### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by binkley** [takari/polyglot-maven#67]
Kotlin polyglot support would be appreciated.

**Comment by huntc** [comment]
A PR would be appreciated also. ;-)

**Comment by jvanzyl** [comment]
I have no idea what I'm doing really, but I tried something quite a while ago. i pushed the branch if you want to take a look:

https://github.com/takari/polyglot-maven/tree/kotlin/polyglot-kotlin

**Comment by lion7** [comment]
My attempt to improve the current implementation a bit: https://github.com/takari/polyglot-maven/pull/184

**Comment by Tradunsky** [comment]
I think the issue could be closed now.
@mosabua WDYT?
