### ISSUE TITLE
Sort Model

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#80]
full model looks like
![image](https://cloud.githubusercontent.com/assets/1614482/14565642/a3d0d904-035e-11e6-9e33-d852fe3969f6.png)

**Comment by paulvi** [comment]
Found http://maven.apache.org/developers/conventions/code.html#POM_Code_Convention from http://www.mojohaus.org/tidy-maven-plugin/pom-mojo.html

**Comment by sveryovka** [comment]
Please be more specific. Please describe issue in more details

**Comment by paulvi** [comment]
While the documentation http://maven.apache.org/developers/conventions/code.html#POM_Code_Convention recommends one order of pom elements,  
it is different in code of maven Model.

The resolution would be to rearrange order of elements in code to bring it close to recommended pom.

**Comment by mosabua** [comment]
The order should NOT matter for it to work just like in the original pom.xml. However for reformatting you can follow what the tidy plugin uses. http://www.mojohaus.org/tidy-maven-plugin/

**Comment by paulvi** [comment]
Thanks  @mosabua for pointing to new maven plugin.

The origin issue was about Model.java, and not about any pom.xml.
