### ISSUE TITLE
Support for maven-tiles

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#82]
maven-tiles https://github.com/repaint-io/maven-tiles allows to have parts of build definition in separate files. Having part of build in parts can enable quicker adoption of polyglot thinking,
and skip problem of having to translate parts, e.g. when find an example of plugin configuration.

Possibly this issue should sound like "support translating parts of pom"

ref https://github.com/repaint-io/maven-tiles/issues/61

**Comment by jvanzyl** [comment]
This is really the parameterized mixin and isn't just a polyglot issue, and it should just work transparently. I'm not keen on support any functionality model-wise that is not supported in Maven itself.

**Comment by paulvi** [comment]
@jvanzyl Jason, it is not about just you and your time.

Both projects are great effort for extending Maven. Is it "only we are great", or "let's look what great can come out of these things put together".

Or maybe you can point to an alternative that is already in use..

**Comment by mkristian** [comment]
@paulvi with ruby and groovy you can easily achieve such mixins. feels like just pick the right flavor of poms then you get "tiles" for free.

**Comment by jvanzyl** [comment]
All I'm saying is that I'm not adding support for any specific plugin implementation. If there's a general problem sure that needs to be fixed.

**Comment by talios** [comment]
I did some quick experimentation on a fresh empty project with a simple tile definition.  @jvanzyl whilst not a tile specific issue, I think there is a problem here with polyglot-maven itself ( or more, the model readers/writers ) in relation to MOJO configuration - which from memory is represented as just a DOM node - and essentially no-mands-land when it comes to the different formats.

The simple project has this plugin defined:

      <plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <version>2.8</version>
        <extensions>true</extensions>
        <configuration>
          <tiles>
            <tile>com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)</tile>
            <tile>com.smxemail.tiles:com.smxemail.tiles.enforcements:[2.0.0,3.0.0)</tile>
            <tile>com.smxemail.tiles:com.smxemail.tiles.osgiservices:[2.0.0,3.0.0)</tile>
            <tile>com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)</tile>
          </tiles>
        </configuration>
      </plugin>

The `atom` format converts this to:

    plugin
      id: io.repaint.maven:tiles-maven-plugin:2.8
      tiles: [
        tile: "com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)"
        tile: "com.smxemail.tiles:com.smxemail.tiles.enforcements:[2.0.0,3.0.0)"
        tile: "com.smxemail.tiles:com.smxemail.tiles.osgiservices:[2.0.0,3.0.0)"
        tile: "com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)"
      ]

This correctly pulls out each `<tile>` from the configuration, but fails to do anything with `<extensions>true</extensions>`, whilst the `yaml` format returns:

      - groupId: io.repaint.maven
        artifactId: tiles-maven-plugin
        version: 2.8
        extensions: true
        configuration:
          tiles: {tile: 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)'}

which _does_ pull out the `extensions`, but only keeps the last `<tile>` definition.

The `ruby` version:

      plugin( 'io.repaint.maven:tiles-maven-plugin:2.8',
          'tiles' => [ 'com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)',
                       'com.smxemail.tiles:com.smxemail.tiles.enforcements:[2.0.0,3.0.0)',
                       'com.smxemail.tiles:com.smxemail.tiles.osgiservices:[2.0.0,3.0.0)',
                       'com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)' ] )

gets all the tile definitions, but also skips the `execution`.

Groovy gets it all correct:

      plugin {
        groupId 'io.repaint.maven'
        artifactId 'tiles-maven-plugin'
        version '2.8'
        extensions 'true'
        configuration {
          tiles {
            tile 'com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)'
            tile 'com.smxemail.tiles:com.smxemail.tiles.enforcements:[2.0.0,3.0.0)'
            tile 'com.smxemail.tiles:com.smxemail.tiles.osgiservices:[2.0.0,3.0.0)'
            tile 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)'
          }
        }
      }

and the `scala` variant just NPEs.

I just tried adding the atom extension to the project and added the missing `extensions: true` bit, but tiles never seemed to kick in so it might not even be reading it.  The ruby extension just seemed to explode with a lot of internal ruby looking errors.  Groovy however worked a charm!

    $ mvn -f pom.groovy clean install
    [INFO] Scanning for projects...
    [INFO] --- tiles-maven-plugin: Injecting 4 tiles as intermediary parent artifact's...
    [INFO] Mixed 'com.talios.test:polyglot-tiles:1.0-SNAPSHOT' with tile 'com.smxemail.tiles:com.smxemail.tiles.release:2.0.8' as it's new parent.
    [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.release:2.0.8' with tile 'com.smxemail.tiles:com.smxemail.tiles.enforcements:2.0.4' as it's new parent.
    [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.enforcements:2.0.4' with tile 'com.smxemail.tiles:com.smxemail.tiles.osgiservices:2.0.1' as it's new parent.
    [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.osgiservices:2.0.1' with tile 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:2.0.1' as it's new parent.
    [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:2.0.1' with original parent '(no parent)' as it's  new top level parent.

Assuming these things get fixed ( we should raise them as independent, not related to tiles issues tho ) then I don't see any reason for the other variants to not just work as well.

**Comment by rvowles** [comment]
@talios you are hitting an issue with yaml itself there, it cannot handle more than one key named the same thing in the same "hash". Ansible suffers greatly from this.

**Comment by paulvi** [comment]
Now I am 100% sure who wrote README at https://github.com/repaint-io/maven-tiles

@talios, hint: add `- [ ]` that would be converted to checkbox, and the result will be even visible from issue list

- [ ] make sure all raised issues are solved or raised as an issue
- [ ] for YAML there is already open issue #62

**Comment by mkristian** [comment]
@paulvi I assume you did convert the xml into the various pom DSL? if yes, will fix the ruby bits.

but the conversion from the internal model DOM into some pom representation does not indicate that the DSL is broken. I am sure 
```ruby
plugin( 'io.repaint.maven:tiles-maven-plugin:2.8',
      :extensions => true,
      'tiles' => [ 'com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)',
                   'com.smxemail.tiles:com.smxemail.tiles.enforcements:[2.0.0,3.0.0)',
                   'com.smxemail.tiles:com.smxemail.tiles.osgiservices:[2.0.0,3.0.0)',
                   'com.smxemail.tiles:com.smxemail.tiles.karaffeature:[2.0.0,3.0.0)' ] )
```
will work as expected.

**Comment by paulvi** [comment]
@talios DONE, all issues as separate tickets #62, #86, #87, #88

@mkristian Christian, the trying out and comparison https://github.com/takari/polyglot-maven/issues/82#issuecomment-211826469 is made by @talios Mark , not me. I have not decided on flavor, was betting on YAML, but now it looks that only Groovy is bug free for now.

**Comment by mkristian** [comment]
@paulvi sorry - wrong pick :)

**Comment by mkristian** [comment]
and thanx for splitting this up

**Comment by paulvi** [comment]
@mkristian for https://github.com/takari/polyglot-maven/issues/82#issuecomment-211410349 comments

nothing is for free. There is Babylon Tower problem #15 when developers used different languages and cannot freely reuse them.

And maven-tiles idea allows to gradually transit to a flavor or mix them (Note: I still have to try out well https://github.com/repaint-io/maven-tiles/issues/62#)

**Comment by talios** [comment]
@mkristian That was me who added those examples, and yes - I was using the converter tool to generate the different flavours, so they're not writing out the extensions element.
