### ISSUE TITLE
[question] What is atom?

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#91]
Is https://en.wikipedia.org/wiki/Atom_(programming_language) correct reference for atom language ?

Asking as every time I open website link from there and go to http://hackage.haskell.org/package/atom it seems that I came to wrong place

ref #73

**Comment by paulvi** [comment]
rename to Haskell Atom ?

**Comment by jvanzyl** [comment]
Declarative format inspired by the Google Blaze. Dhanji is a xoogler.

**Comment by paulvi** [comment]
- Google Blaze
- Dhanji 
- xoogler

they are all new words

Please collaborate a bit and give exact link, as Atom is already ambiguous name.

**Comment by paulvi** [comment]
<img width="876" alt="screen shot 2016-04-24 at 11 57 30 pm" src="https://cloud.githubusercontent.com/assets/1614482/14768572/64d583dc-0a78-11e6-828f-ecba0f33a876.png">

I am doing some Eclipse Editors

**Comment by jvanzyl** [comment]
I wouldn't spend any time making an editor for it. Dhanji Prasanna is a person who used to work at Google (common referred to as a Xoogler) who borrow ideas for this format from the internal Blaze build tool which has been open sourced and is now called Bazel.

**Comment by paulvi** [comment]
OK, so this atom flavour is actually atom(Blaze/Bazel inspired), and not related to Haskel.

Is it right?

As for Editor, that will be and is already minimal Editor for some coloring.
