### ISSUE TITLE
Badge for current version and license

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#94]
It is possible to show Badge for current version and license in README
Look at https://github.com/mojohaus/versions-maven-plugin#mojohaus-versions-maven-plugin example

[![Apache License, Version 2.0, January 2004](https://img.shields.io/github/license/mojohaus/versions-maven-plugin.svg?label=License)](http://www.apache.org/licenses/)
[![Maven Central](https://img.shields.io/maven-central/v/org.codehaus.mojo/versions-maven-plugin.svg?label=Maven%20Central)](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.mojo%22%20AND%20a%3A%22versions-maven-plugin%22)

ref #93

**Comment by mosabua** [comment]
Done
