### ISSUE TITLE
A required class was missing while executing io.takari.polyglot:polyglot-translate-plugin:0.1.16:translate

### ISSUE THREAD

**Issue by grafandreas** [takari/polyglot-maven#96]
Dear all, 

while executing 
mvn io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=/XXX/pom.xml -Doutput=pomt.rb

I am seeing this error:

[ERROR] Failed to execute goal io.takari.polyglot:polyglot-translate-plugin:0.1.16:translate (default-cli) on project standalone-pom: Execution default-cli of goal io.takari.polyglot:polyglot-translate-plugin:0.1.16:translate failed: A required class was missing while executing io.takari.polyglot:polyglot-translate-plugin:0.1.16:translate: org/codehaus/plexus/util/xml/XmlStreamReader

For some reason, mvn downloads

[INFO] --- polyglot-translate-plugin:0.1.16:translate (default-cli) @ standalone-pom ---
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (165 KB at 244.2 KB/sec)

And that version of plexus-utils does not seem to have the XmlStreamReader Class in its ja.r

Any ideas how to fix this?

Best Regards,

Andreas

**Comment by grafandreas** [comment]
Seems to be a regression, using version 0.1.15 
mvn io.takari.polyglot:polyglot-translate-plugin:0.1.15:translate
Seems to work fine.

**Comment by scottcarey** [comment]
I have the same problem with 0.2.0.  Tried the plugin for the first time, and it fails with the above error:

> [ERROR] Failed to execute goal io.takari.polyglot:polyglot-translate-plugin:0.2.0:translate (default-cli) on project core: Execution default-cli of goal io.takari.polyglot:polyglot-translate-plugin:0.2.0:translate failed: A required class was missing while executing io.takari.polyglot:polyglot-translate-plugin:0.2.0:translate: org/codehaus/plexus/util/xml/XmlStreamReader

I tried updating to maven 3.5, but that did not help.

Should this be re-opened?  or create a new issue?

**Comment by lefou** [comment]
I can confirm this issue still exists.

I worked around this issue with adding a dependency to the plugin in pom.

```xml
          <plugin>
            <groupId>io.takari.polyglot</groupId>
            <artifactId>polyglot-translate-plugin</artifactId>
            <version>0.2.0</version>
            <dependencies>
              <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-utils</artifactId>
                <version>3.0.24</version>
              </dependency>
            </dependencies>
            <executions>
              <execution>
                <id>pom-scala-to-pom-xml</id>
                <phase>initialize</phase>
                <goals>
                  <goal>translate-project</goal>
                </goals>
                <configuration>
                  <input>pom.scala</input>
                  <output>pom.xml</output>
                </configuration>
              </execution>
            </executions>
          </plugin>
```
